  
language: cpp

matrix:
  include:
    - os: linux
      arch: arm64
      sudo: required
      before_install:
        - sudo apt update
        - sudo apt install libsdl2-dev
    - os: linux
      arch: amd64
      sudo: required
      before_install:
        - sudo apt update
        - sudo apt install libsdl2-dev
    - os: windows
      arch: amd64
      before_install:
        - powershell -c "Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope LocalMachine"
        - powershell -c "Import-Module PackageManagement; Install-PackageProvider Nuget"
        - powershell -c "Import-Module PackageManagement; Register-PackageSource -Name NuGetOrg -Location https://www.nuget.org/api/v2 -ProviderName NuGet"
        - powershell -c "Import-Module PackageManagement; Install-Package -Source NuGetOrg -Name NuGet.CommandLine -Force -ExcludeVersion -Destination C:\tools"
        - Install-Package sdl2.nuget -Version 2.0.10
        - choco install make
    - os: osx
      before_install:
        - brew update
        - brew install sdl2
     

script:
- cd test
- make
- ./test
- cd ..
- make
