  
language: cpp

matrix:
  include:
    - os: linux
      arch: arm64
      sudo: required
      before_install:
        - sudo apt update
        - sudo apt install libsdl2-dev
    - os: linux
      arch: amd64
      sudo: required
      before_install:
        - sudo apt update
        - sudo apt install libsdl2-dev
    - os: windows
      arch: amd64
      before_install:
      - |-
      case $TRAVIS_OS_NAME in
        windows)
          [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
          choco upgrade --no-progress -y msys2
          taskkill //IM gpg-agent.exe //F
          ;;
      esac
    - os: osx
      before_install:
        - brew update
        - brew install sdl2
     

script:
- cd test
- make
- ./test
- cd ..
- make
