  
language: cpp

matrix:
  include:
    - os: linux
      arch: arm64
      sudo: required
      before_install:
        - sudo apt update
        - sudo apt install libsdl2-dev
    - os: linux
      arch: amd64
      sudo: required
      before_install:
        - sudo apt update
        - sudo apt install libsdl2-dev
    - os: windows
      arch: amd64
      before_install:
        - echo $PATH
        - echo $UNAME_S
        - mkdir /lib
        - wget https://www.libsdl.org/release/SDL2-devel-2.0.10-mingw.tar.gz
        - tar -xf SDL2-devel-2.0.10-mingw.tar.gz -C /lib
        - PATH=$PATH:/lib
        - choco install make
    - os: osx
      before_install:
        - brew update
        - brew install sdl2
     

script:
- cd test
- make
- ./test
- cd ..
- make
