  
language: cpp

matrix:
  include:
    - os: linux
      arch: arm64
      sudo: required
      before_install:
        - sudo apt update
        - sudo apt install libsdl2-dev
    - os: linux
      arch: amd64
      sudo: required
      before_install:
        - sudo apt update
        - sudo apt install libsdl2-dev
    - os: windows
      arch: amd64
      before_install:
        - rm -rf C:/tools/msys64
        - choco uninstall -y mingw
        - choco upgrade --no-progress -y msys2
        - export msys2='cmd //C RefreshEnv.cmd '
        - export msys2+='& set MSYS=winsymlinks:nativestrict '
        - export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
        - export mingw64="$msys2 -mingw64 -full-path -here -c "\"\$@"\" --"
        - export msys2+=" -msys2 -c "\"\$@"\" --"
        - $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-toolchain
        - taskkill //IM gpg-agent.exe //F  # https://travis-ci.community/t/4967
        - export PATH=/C/tools/msys64/mingw64/bin:$PATH
        - export MAKE=mingw32-make  # so that Autotools can find it
        - wget https://www.libsdl.org/release/SDL2-devel-2.0.10-mingw.tar.gz
        - pacman -Syyu
        #- tar -xf SDL2-devel-2.0.10-mingw.tar.gz
        #- cd SDL2-2.0.10
        #- cp -r x86_64-w64-mingw32 /c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64
        #- cd ..
        #- choco install make -version 4.3
      before_cache:
        $msys2 pacman --sync --clean --noconfirm
      cache:
        directories:
        - $HOME/AppData/Local/Temp/chocolatey
        - /C/tools/msys64
    - os: osx
      before_install:
        - brew update
        - brew install sdl2
    
script:
- cd test
- make
- ./test
- cd ..
- make


deploy:
  provider: releases
  api_key: $GITHUB_OATH
  file: "cosmic.exe"
  skip_cleanup: true
  draft: true
  on:
    branch: travis
    tags: true
